/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GameRouteImport } from './routes/game'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameIndexRouteImport } from './routes/game.index'
import { Route as GamePersonPersonIdRouteImport } from './routes/game.person.$personId'
import { Route as GameMovieMovieIdRouteImport } from './routes/game.movie.$movieId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameRoute,
} as any)
const GamePersonPersonIdRoute = GamePersonPersonIdRouteImport.update({
  id: '/person/$personId',
  path: '/person/$personId',
  getParentRoute: () => GameRoute,
} as any)
const GameMovieMovieIdRoute = GameMovieMovieIdRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => GameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game': typeof GameRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/game/': typeof GameIndexRoute
  '/game/movie/$movieId': typeof GameMovieMovieIdRoute
  '/game/person/$personId': typeof GamePersonPersonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/game': typeof GameIndexRoute
  '/game/movie/$movieId': typeof GameMovieMovieIdRoute
  '/game/person/$personId': typeof GamePersonPersonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game': typeof GameRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/game/': typeof GameIndexRoute
  '/game/movie/$movieId': typeof GameMovieMovieIdRoute
  '/game/person/$personId': typeof GamePersonPersonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game'
    | '/login'
    | '/logout'
    | '/signup'
    | '/game/'
    | '/game/movie/$movieId'
    | '/game/person/$personId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/game'
    | '/game/movie/$movieId'
    | '/game/person/$personId'
  id:
    | '__root__'
    | '/'
    | '/game'
    | '/login'
    | '/logout'
    | '/signup'
    | '/game/'
    | '/game/movie/$movieId'
    | '/game/person/$personId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/'
      fullPath: '/game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof GameRoute
    }
    '/game/person/$personId': {
      id: '/game/person/$personId'
      path: '/person/$personId'
      fullPath: '/game/person/$personId'
      preLoaderRoute: typeof GamePersonPersonIdRouteImport
      parentRoute: typeof GameRoute
    }
    '/game/movie/$movieId': {
      id: '/game/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/game/movie/$movieId'
      preLoaderRoute: typeof GameMovieMovieIdRouteImport
      parentRoute: typeof GameRoute
    }
  }
}

interface GameRouteChildren {
  GameIndexRoute: typeof GameIndexRoute
  GameMovieMovieIdRoute: typeof GameMovieMovieIdRoute
  GamePersonPersonIdRoute: typeof GamePersonPersonIdRoute
}

const GameRouteChildren: GameRouteChildren = {
  GameIndexRoute: GameIndexRoute,
  GameMovieMovieIdRoute: GameMovieMovieIdRoute,
  GamePersonPersonIdRoute: GamePersonPersonIdRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
